name: Feature Request
description: Propose a new feature or enhancement for StatefulREPL
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for proposing a feature! The Loom thrives on bounded claims and verifiable oracles. Help us understand your vision.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What tension exists?
      placeholder: "When coordinating multiple agents, I can't..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution. Include claims and contracts if applicable.
      placeholder: |
        CLAIM-001: "Adding X would improve Y" [scope: module] [confidence: 0.8]
        CONTRACT-001: Proposed interface with PRE/POST/INV...
    validations:
      required: true

  - type: dropdown
    id: phase
    attributes:
      label: Phase Alignment
      description: Which implementation phase does this feature belong to?
      options:
        - "Phase 1: MVP (Complete)"
        - "Phase 2: Core Features (Complete)"
        - "Phase 3: Multi-Agent (In Progress)"
        - "Phase 4: Advanced (Future)"
        - "Not sure / Needs discussion"
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component Affected
      description: Which component(s) would this feature touch?
      multiple: true
      options:
        - Loom State (L1/L2/L3)
        - Quality Evaluator
        - Hallucination Detector
        - Event Sourcing
        - Orchestrator/Saga
        - Planner (HALO)
        - Sandbox Executor
        - CLI
        - Server/API
        - Model Abstraction
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: oracle
    attributes:
      label: Oracle (Success Criteria)
      description: How will we verify this feature works? What would falsify success?
      placeholder: |
        Success: Agent handoffs complete in <2s with 0 data loss
        Failure: Any dropped context or timeout >5s
    validations:
      required: true

  - type: checkboxes
    id: loom_protocol
    attributes:
      label: Loom Protocol Alignment
      description: Does this feature align with The Loom's principles?
      options:
        - label: "Presence-first: Grounds in observable truth, not speculation"
        - label: "Verifiable: Includes testable claims and oracles"
        - label: "Bounded: Defines scope, confidence, falsification criteria"
        - label: "Integrative: Honors contradictions without forced resolution"

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other solutions did you consider? Why is this approach better?
    validations:
      required: false

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Hints
      description: |
        Any hints about implementation? Dependencies? Breaking changes?
      placeholder: |
        - Would require adding dependency X
        - Breaks backward compatibility in module Y
        - Could leverage existing Z pattern
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context, mockups, references, or research
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues/PRs to avoid duplicates
          required: true
        - label: I have defined success criteria (oracle)
          required: true
        - label: I understand this may be deferred based on phase priority
          required: true
